# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.today)),
                ('contrasena', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
